### ISSUE TITLE
Two bugs in map

### ISSUE THREAD

**Issue by panther2** [triplea-maps/great_war#1]
As reported at the TripleA repo: https://github.com/triplea-game/triplea/issues/1331

> Rogue77-NL commented ,,,
>Hello,
>The map Great War contains two bugs.

>Land territory 'Corsica' is counted as sea zone 'SZ 51 Ligurian Sea'.
>This was already the case in previous versions, judging by the territory name shown in the bottom left corner of the game window, but I was able to move land units to 'Corsica' nevertheless. Since the latest update of the game to version 1.9 the latter is not possible anymore. The infantry unit present at 'Corsica' at the beginning of a game can still be selected.

>Land territory 'Songea' and sea zone 'SZ 71 Mozambique Channel' are adjacent to eachother; this seems unintentional.
This bug was too minor for me to report separately, but the Corsica thing is influencing gameplay more significantly, so if I'm submitting a report anyway... :)
Thanks in advance for your time!

**Comment by Rogue77-NL** [comment]
Thank you for referring this issue to the right place. I'm just following instructions. :) Kind regards.

**Comment by Rogue77-NL** [comment]
Thank you for referring this issue to the right place. I'm just following instructions. :) Kind regards!

**Comment by simon33-2** [comment]
Ok, I can see the connection between SZ 71 and Songea. Happy to submit a pull request to remove it.

I don't understand the first problem. How can a land territory be counted as a SZ? What do you mean? Shouldn't you only be able to move land units to or from Corsica via a Transport? Seems exactly what happens.

@Rogue77-NL

**Comment by simon33-2** [comment]
@panther2 

Do you understand the first part of this issue?

**Comment by panther2** [comment]
@simon33-2 

Yes, when you hover over the island Corsica, it is not indicated as "Corsica" but as "SZ 51 Ligurian Sea" instead. 
In other words: the seazone-polygons are overlaying the island polygons. I suppose it occurred when creating the polygons.txt:

From http://tripleamaps.sourceforge.net/old/doc/map_and_map_skin_making_overview.html#sec_4.1.3

> The polygon grabber utility comes with a special "Island Mode" feature. It has been known that when dealing with many islands in one sea zone causes a visual problem. Doing the sea zone first will cover up any islands inside. This will leave the user unaware if the islands have been selected or not. The "Island Mode" feature helps over come this by out-lining selected territories in red and not filling them in with yellow, as is the default. Look at figures 4.1.3.1 and 4.1.3.2 for examples of "Island Mode" at work.

**Comment by jakobschonberg** [comment]
SZ 51 Ligurian Sea overlaps Corsica, to fix it change the "SZ 51 Ligurian Sea"-line in polygons.txt to:
`SZ 51 Ligurian Sea  <  (1539,1339) (1539,1339) (1540,1338) (1541,1338) (1541,1333) (1543,1331) (1543,1330) (1544,1329) (1544,1328) (1545,1327) (1549,1327) (1550,1326) (1551,1326) (1553,1324) (1553,1323) (1555,1321) (1559,1321) (1562,1318) (1565,1318) (1568,1321) (1568,1324) (1569,1325) (1569,1326) (1574,1326) (1576,1328) (1576,1331) (1578,1333) (1578,1335) (1580,1335) (1582,1337) (1582,1339) (1583,1339) (1584,1340) (1585,1340) (1587,1342) (1587,1343) (1588,1344) (1589,1344) (1591,1346) (1591,1349) (1592,1349) (1593,1350) (1593,1351) (1594,1351) (1596,1353) (1597,1353) (1599,1355) (1600,1355) (1601,1356) (1602,1356) (1604,1358) (1604,1365) (1605,1366) (1605,1367) (1606,1368) (1606,1369) (1607,1369) (1609,1371) (1609,1372) (1610,1373) (1610,1374) (1611,1375) (1611,1376) (1613,1378) (1613,1390) (1615,1392) (1615,1393) (1616,1394) (1617,1394) (1618,1395) (1618,1418) (1623,1423) (1623,1425) (1627,1429) (1627,1505) (1588,1420) (1585,1423) (1584,1423) (1584,1427) (1582,1429) (1581,1429) (1580,1430) (1580,1433) (1582,1433) (1583,1434) (1583,1436) (1584,1437) (1584,1438) (1585,1439) (1585,1449) (1584,1450) (1584,1452) (1582,1454) (1582,1455) (1581,1456) (1580,1456) (1578,1458) (1577,1458) (1574,1461) (1574,1469) (1575,1470) (1575,1471) (1577,1471) (1578,1472) (1578,1473) (1579,1474) (1579,1475) (1576,1478) (1574,1478) (1574,1481) (1573,1482) (1573,1490) (1572,1491) (1571,1491) (1569,1493) (1563,1493) (1561,1491) (1560,1491) (1559,1490) (1559,1486) (1558,1485) (1557,1485) (1556,1484) (1556,1483) (1554,1481) (1554,1470) (1555,1469) (1556,1469) (1556,1468) (1557,1467) (1557,1462) (1554,1459) (1554,1457) (1553,1456) (1553,1455) (1552,1454) (1551,1454) (1550,1453) (1550,1452) (1549,1451) (1549,1449) (1552,1446) (1552,1443) (1553,1442) (1554,1442) (1554,1434) (1556,1432) (1560,1432) (1560,1432) (1565,1427) (1566,1427) (1566,1425) (1567,1424) (1570,1424) (1570,1423) (1572,1421) (1574,1421) (1574,1420) (1575,1419) (1575,1412) (1578,1409) (1583,1409) (1585,1411) (1585,1415) (1588,1418) (1588,1420) (1627,1505) (1626,1506) (1504,1506) (1503,1505) (1503,1357) (1506,1354) (1508,1354) (1509,1353) (1512,1353) (1513,1352) (1519,1352) (1522,1349) (1531,1349) (1534,1346) (1534,1345) (1538,1341) (1538,1340) > `

**Comment by ron-murhammer** [comment]
@panther2 These issues should be resolved now.
